
### log levels
# debug -1
# info 0
# warn 1
# error 2

log_file:
  path: ${CAL_LOGFILE_PATH}
  level: ${CAL_LOG_LEVEL}

sql_db:
  host: ${CAL_DB_HOST}
  port: ${CAL_DB_PORT}
  login: ${CAL_DB_USER}
  password: ${CAL_DB_PASSWORD}
  database: ${CAL_DB_NAME}

http_server:
  host: ${CAL_HTTP_HOST}
  port: ${CAL_HTTP_PORT}

storage:
  sql: true

grpc_server:
  host: ${CAL_GRPC_HOST}
  port: ${CAL_GRPC_PORT}

amqp:
  url: ${CAL_Q_URL}
  exchange: ""
  name: ${CAL_Q_QUEUE}
  qos: 1