version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${CAL_DB_LOGIN}
      POSTGRES_PASSWORD: ${CAL_DB_PASSWORD}
      POSTGRES_DB: ${CAL_DB_NAME}

  adminer:
    image: adminer
    ports:
      - 8081:8080